stages:
    - build

.base_template : &BASE
   script:
   - /usr/bin/docker run --gpus '"device=0"' -v .:/data nvcr.io/nvidia/pytorch:19.12-py3
     /bin/bash -c "nvidia-smi && ls /data"


build-ci-test:
    stage: build
    tags:
    - test
    <<: *BASE
